import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { useToast } from "@/hooks/use-toast";
import { Calendar, Download, FileText, Send } from "lucide-react";
import { useState } from "react";
import jsPDF from 'jspdf';

const recentReports = [
  {
    name: "Q2 2024 ESG Report",
    date: "2024-06-30",
    status: "completed",
    type: "Quarterly",
    size: "2.4 MB"
  },
  {
    name: "May 2024 Monthly Report",
    date: "2024-05-31",
    status: "completed",
    type: "Monthly",
    size: "1.8 MB"
  },
  {
    name: "April 2024 Monthly Report",
    date: "2024-04-30",
    status: "completed",
    type: "Monthly",
    size: "2.1 MB"
  },
];

export const ESGReports = () => {
  const { toast } = useToast();
  const [reportForm, setReportForm] = useState({
    name: "",
    type: "",
    startDate: "2024-07-01",
    endDate: "2024-09-30",
    notes: ""
  });
  const [isGenerating, setIsGenerating] = useState(false);

  const generatePDF = (reportName: string, reportDate: string, reportType: string) => {
    const doc = new jsPDF();
    
    // Header
    doc.setFontSize(20);
    doc.text('CarbonIQ ESG Report', 20, 30);
    
    doc.setFontSize(16);
    doc.text(reportName, 20, 50);
    
    doc.setFontSize(12);
    doc.text(`Report Type: ${reportType}`, 20, 70);
    doc.text(`Generated Date: ${reportDate}`, 20, 80);
    doc.text(`Period: Q3 2024`, 20, 90);
    
    // Section 1: Executive Summary
    doc.setFontSize(14);
    doc.text('Executive Summary', 20, 110);
    doc.setFontSize(10);
    const summaryText = `This ESG report provides comprehensive insights into our environmental, social, and governance performance for the reporting period. Our carbon emissions decreased by 15% compared to the previous quarter, demonstrating our commitment to sustainability.`;
    const splitSummary = doc.splitTextToSize(summaryText, 170);
    doc.text(splitSummary, 20, 120);
    
    // Section 2: Emissions Data
    doc.setFontSize(14);
    doc.text('Carbon Emissions Overview', 20, 150);
    doc.setFontSize(10);
    doc.text('Scope 1 Emissions: 245.6 tCO₂e', 20, 160);
    doc.text('Scope 2 Emissions: 1,892.3 tCO₂e', 20, 170);
    doc.text('Scope 3 Emissions: 4,567.8 tCO₂e', 20, 180);
    doc.text('Total Emissions: 6,705.7 tCO₂e', 20, 190);
    
    // Section 3: Key Metrics
    doc.setFontSize(14);
    doc.text('Key Performance Indicators', 20, 210);
    doc.setFontSize(10);
    doc.text('• Energy Consumption: 12,345 MWh', 20, 220);
    doc.text('• Renewable Energy %: 68%', 20, 230);
    doc.text('• Water Usage: 45,678 gallons', 20, 240);
    doc.text('• Waste Diverted from Landfill: 89%', 20, 250);
    
    // Footer
    doc.setFontSize(8);
    doc.text('Generated by CarbonIQ Platform - Confidential', 20, 280);
    
    return doc;
  };

  const handleGenerateReport = async (e: React.FormEvent) => {
    e.preventDefault();
    
    if (!reportForm.name || !reportForm.type) {
      toast({
        title: "Missing Information",
        description: "Please fill in the report name and type",
        variant: "destructive",
      });
      return;
    }

    setIsGenerating(true);
    
    // Simulate report generation
    setTimeout(() => {
      // Generate and download PDF
      const pdf = generatePDF(reportForm.name, new Date().toLocaleDateString(), reportForm.type);
      pdf.save(`${reportForm.name.replace(/\s+/g, '-').toLowerCase()}.pdf`);
      
      toast({
        title: "Report Generated Successfully",
        description: `${reportForm.name} has been generated and downloaded`,
      });
      setIsGenerating(false);
      
      // Reset form
      setReportForm({
        name: "",
        type: "",
        startDate: "2024-07-01",
        endDate: "2024-09-30",
        notes: ""
      });
    }, 2000);
  };

  const handleDownloadReport = (reportName: string) => {
    // Generate PDF for existing reports
    const reportDate = new Date().toLocaleDateString();
    const reportType = reportName.includes('Monthly') ? 'Monthly' : 'Quarterly';
    
    const pdf = generatePDF(reportName, reportDate, reportType);
    pdf.save(`${reportName.replace(/\s+/g, '-').toLowerCase()}.pdf`);
    
    toast({
      title: "Download Complete",
      description: `${reportName} has been downloaded`,
    });
  };

  const handleShareReport = (reportName: string) => {
    navigator.clipboard.writeText(`${window.location.origin}/reports/share/${reportName.toLowerCase().replace(/\s+/g, '-')}`);
    toast({
      title: "Share Link Copied",
      description: "The shareable link has been copied to your clipboard",
    });
  };

  const useTemplate = (templateName: string) => {
    setReportForm(prev => ({
      ...prev,
      name: `${templateName} - ${new Date().toLocaleDateString()}`,
      type: "quarterly"
    }));
    
    toast({
      title: "Template Applied",
      description: `${templateName} template has been applied to the form`,
    });
  };

  return (
    <div className="space-y-6 animate-fade-in">
      <div className="flex items-center justify-between">
        <div>
          <h1 className="text-3xl font-bold tracking-tight">ESG Reports</h1>
          <p className="text-muted-foreground">
            Generate compliance reports for ESG submission and stakeholder communication
          </p>
        </div>
        <Button onClick={() => document.getElementById('generate-form')?.scrollIntoView({ behavior: 'smooth' })}>
          <FileText className="w-4 h-4 mr-2" />
          Generate Report
        </Button>
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
        {/* Report Generator */}
        <Card id="generate-form">
          <CardHeader>
            <CardTitle>Create New Report</CardTitle>
            <CardDescription>
              Generate comprehensive ESG compliance reports
            </CardDescription>
          </CardHeader>
          <CardContent>
            <form onSubmit={handleGenerateReport} className="space-y-4">
              <div className="space-y-2">
                <Label htmlFor="report-name">Report Name</Label>
                <Input 
                  id="report-name" 
                  placeholder="Q3 2024 ESG Report"
                  value={reportForm.name}
                  onChange={(e) => setReportForm(prev => ({ ...prev, name: e.target.value }))}
                  required
                />
              </div>

              <div className="space-y-2">
                <Label htmlFor="report-type">Report Type</Label>
                <Select value={reportForm.type} onValueChange={(value) => setReportForm(prev => ({ ...prev, type: value }))}>
                  <SelectTrigger>
                    <SelectValue placeholder="Select report type" />
                  </SelectTrigger>
                  <SelectContent>
                    <SelectItem value="monthly">Monthly Report</SelectItem>
                    <SelectItem value="quarterly">Quarterly Report</SelectItem>
                    <SelectItem value="annual">Annual Report</SelectItem>
                    <SelectItem value="custom">Custom Period</SelectItem>
                  </SelectContent>
                </Select>
              </div>

              <div className="grid grid-cols-2 gap-4">
                <div className="space-y-2">
                  <Label htmlFor="start-date">Start Date</Label>
                  <Input 
                    id="start-date" 
                    type="date"
                    value={reportForm.startDate}
                    onChange={(e) => setReportForm(prev => ({ ...prev, startDate: e.target.value }))}
                  />
                </div>
                <div className="space-y-2">
                  <Label htmlFor="end-date">End Date</Label>
                  <Input 
                    id="end-date" 
                    type="date"
                    value={reportForm.endDate}
                    onChange={(e) => setReportForm(prev => ({ ...prev, endDate: e.target.value }))}
                  />
                </div>
              </div>

              <div className="space-y-2">
                <Label htmlFor="scope">Emission Scopes</Label>
                <div className="flex gap-2">
                  <Badge variant="default">Scope 2</Badge>
                  <Badge variant="default">Scope 3</Badge>
                </div>
              </div>

              <div className="space-y-2">
                <Label htmlFor="notes">Additional Notes</Label>
                <Textarea 
                  id="notes"
                  placeholder="Include any specific context or methodology notes..."
                  rows={3}
                  value={reportForm.notes}
                  onChange={(e) => setReportForm(prev => ({ ...prev, notes: e.target.value }))}
                />
              </div>

              <Button type="submit" className="w-full" disabled={isGenerating}>
                <FileText className="w-4 h-4 mr-2" />
                {isGenerating ? "Generating..." : "Generate Report"}
              </Button>
            </form>
          </CardContent>
        </Card>

        {/* Report Templates */}
        <Card>
          <CardHeader>
            <CardTitle>Report Templates</CardTitle>
            <CardDescription>
              Pre-configured templates for common ESG frameworks
            </CardDescription>
          </CardHeader>
          <CardContent className="space-y-4">
            <div className="space-y-3">
              <div className="p-4 border rounded-lg hover:bg-accent cursor-pointer transition-colors">
                <div className="flex items-center justify-between">
                  <div>
                    <h4 className="font-medium">GHG Protocol Standard</h4>
                    <p className="text-sm text-muted-foreground">Scope 1, 2, and 3 emissions reporting</p>
                  </div>
                  <Button variant="outline" size="sm" onClick={() => useTemplate("GHG Protocol Standard")}>Use</Button>
                </div>
              </div>

              <div className="p-4 border rounded-lg hover:bg-accent cursor-pointer transition-colors">
                <div className="flex items-center justify-between">
                  <div>
                    <h4 className="font-medium">CDP Climate Report</h4>
                    <p className="text-sm text-muted-foreground">Carbon Disclosure Project format</p>
                  </div>
                  <Button variant="outline" size="sm" onClick={() => useTemplate("CDP Climate Report")}>Use</Button>
                </div>
              </div>

              <div className="p-4 border rounded-lg hover:bg-accent cursor-pointer transition-colors">
                <div className="flex items-center justify-between">
                  <div>
                    <h4 className="font-medium">EU Taxonomy</h4>
                    <p className="text-sm text-muted-foreground">European sustainability reporting</p>
                  </div>
                  <Button variant="outline" size="sm" onClick={() => useTemplate("EU Taxonomy")}>Use</Button>
                </div>
              </div>

              <div className="p-4 border rounded-lg hover:bg-accent cursor-pointer transition-colors">
                <div className="flex items-center justify-between">
                  <div>
                    <h4 className="font-medium">Custom Template</h4>
                    <p className="text-sm text-muted-foreground">Build your own reporting format</p>
                  </div>
                  <Button variant="outline" size="sm" onClick={() => useTemplate("Custom Template")}>Create</Button>
                </div>
              </div>
            </div>
          </CardContent>
        </Card>
      </div>

      {/* Recent Reports */}
      <Card>
        <CardHeader>
          <CardTitle>Recent Reports</CardTitle>
          <CardDescription>
            Download and share previously generated ESG reports
          </CardDescription>
        </CardHeader>
        <CardContent>
          <div className="space-y-4">
            {recentReports.map((report) => (
              <div key={report.name} className="flex items-center justify-between p-4 border rounded-lg">
                <div className="flex items-center gap-4">
                  <FileText className="w-8 h-8 text-primary" />
                  <div>
                    <h4 className="font-medium">{report.name}</h4>
                    <div className="flex items-center gap-2 text-sm text-muted-foreground">
                      <Calendar className="w-4 h-4" />
                      {report.date}
                      <Badge variant="secondary">{report.type}</Badge>
                      <span>{report.size}</span>
                    </div>
                  </div>
                </div>
                
                <div className="flex items-center gap-2">
                  <Button variant="outline" size="sm" onClick={() => handleDownloadReport(report.name)}>
                    <Download className="w-4 h-4 mr-2" />
                    Download PDF
                  </Button>
                  <Button variant="outline" size="sm" onClick={() => handleShareReport(report.name)}>
                    <Send className="w-4 h-4 mr-2" />
                    Share
                  </Button>
                </div>
              </div>
            ))}
          </div>
        </CardContent>
      </Card>

      {/* Export Options */}
      <Card>
        <CardHeader>
          <CardTitle>Export & Automation</CardTitle>
          <CardDescription>
            Configure automatic report generation and distribution
          </CardDescription>
        </CardHeader>
        <CardContent>
          <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
            <div className="space-y-4">
              <h4 className="font-medium">Automated Reports</h4>
              <div className="space-y-3">
                <div className="flex items-center justify-between">
                  <span>Monthly ESG Summary</span>
                  <Badge variant="default">Active</Badge>
                </div>
                <div className="flex items-center justify-between">
                  <span>Quarterly Board Report</span>
                  <Badge variant="secondary">Disabled</Badge>
                </div>
                <div className="flex items-center justify-between">
                  <span>Annual Sustainability Report</span>
                  <Badge variant="default">Active</Badge>
                </div>
              </div>
            </div>

            <div className="space-y-4">
              <h4 className="font-medium">Distribution List</h4>
              <div className="space-y-2">
                <Input placeholder="esg@company.com" />
                <Input placeholder="board@company.com" />
                <Input placeholder="sustainability@company.com" />
              </div>
              <Button variant="outline" className="w-full">
                Add Recipient
              </Button>
            </div>
          </div>
        </CardContent>
      </Card>
    </div>
  );
};
